### ISSUE TITLE
When i build the stencil-todomvc it gave the error.

### ISSUE THREAD

**Issue by kuldeep49291** [derkoe/stencil-todomvc#4]
[ ERROR ]  TypeError: Object.entries is not a function at 
           /home/abc/projects/stencil-todomvc/node_modules/@stencil/core/dist/compiler/index.js:7762:16 at next (native) 
           at fulfilled (/home/abc/projects/stencil-todomvc/node_modules/@stencil/core/dist/compiler/index.js:7738:58)

**Comment by derkoe** [comment]
Stencil released a new not working version 0.3.x - set stencil to version 0.2.3

**Comment by kuldeep49291** [comment]
how many possible to build it. if then yes so please tell us about the
build their project to successfully

**Comment by derkoe** [comment]
I'm not if I understand you. The project can be built with "npm run build" - see also the Travis build https://travis-ci.org/derkoe/stencil-todomvc
